# IMPORTANT:
# If your repo is USERNAME.github.io -> baseURL = "https://USERNAME.github.io/"
# If your repo is anything else (e.g., "portfolio") -> baseURL = "https://USERNAME.github.io/portfolio/"
baseURL = "https://jacob-wheat-acre.github.io/"
languageCode = "en-us"
title = "Jacob Wheat Acre"
theme = "PaperMod"
pagerSize = 10

[params]
  defaultTheme = "auto"        # "light", "dark", or "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true

  # Optional: make the home page list blog posts
  mainSections = ["blog"]

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/USERNAME"
    weight = 40


    [params]

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/jacob-wheat-acre"

    [[params.socialIcons]]
      name = "linkedin"
      url = "https://www.linkedin.com/in/jacob-whitaker-678a8b2b0/"
    
    [[params.socialIcons]]
      name = "youtube"
      url = "https://www.youtube.com/@jacobwhitaker857"

    [[params.socialIcons]]
      name = "facebook"
      url = "https://www.facebook.com/profile.php?id=61581110069615"

    [[params.socialIcons]]
      name = "email"
      url = "mailto:jacob.wheat.acre@gmail.com"
    
